CC = gcc
CFLAGS = -Wall -Werror -Wextra -I ./inc/
PATH_SRC = ./srcs/
PATH_INC = ./inc/
SRC = ./srcs/ft_display.c \
			./srcs/ft_manage_addr.c \
			./srcs/ft_manage_char.c \
			./srcs/ft_manage_char.c \
			./srcs/ft_manage_flags.c \
			./srcs/ft_manage_hex.c \
			./srcs/ft_manage_int.c \
			./srcs/ft_manage_uint.c \
			./srcs/ft_manage_percent.c \
			./srcs/ft_manage_str.c \
			./srcs/ft_manage_type.c \
			./srcs/ft_manage_width.c \
			./srcs/ft_manager.c \
			./srcs/ft_printf.c \
			./srcs/ft_tools.c \
			./srcs/ft_tools2.c

OBJ = ./srcs/ft_display.o \
			./srcs/ft_manage_addr.o \
			./srcs/ft_manage_char.o \
			./srcs/ft_manage_char.o \
			./srcs/ft_manage_flags.o \
			./srcs/ft_manage_hex.o \
			./srcs/ft_manage_int.o \
			./srcs/ft_manage_uint.o \
			./srcs/ft_manage_percent.o \
			./srcs/ft_manage_str.o \
			./srcs/ft_manage_type.o \
			./srcs/ft_manage_width.o \
			./srcs/ft_manager.o \
			./srcs/ft_printf.o \
			./srcs/ft_tools.o \
			./srcs/ft_tools2.o

all : $(OBJ)

clean :
	@rm -f $(OBJ)

re : clean all
